# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  # 配置MySQL数据库
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/db_website?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10240MB
      # 单个文件最大值
      max-file-size: 1024MB
server:
  port: 9999
