# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  # 配置MySQL数据库
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/db_website?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=CONVERT_TO_NULL&&serverTimezone=GMT%2B8
    username: root